version: '3'
services:
    mongodb: # service name / container name 
        image: mongo 
        ports: 
            - 27017:27017
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password123
        volumes: 
            - mongo-data:/data/db # mongo-data <volume name >: /data/db < depends on path defined in image >
        

    mongo-express:
        image: mongo-express
        restart: always
        ports: 
            - 8081:8081
        environment: 
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password123 
            - ME_CONFIG_MONGODB_SERVER=mongodb
        depends_on: 
            - mongodb
    
    myapp:
        image: myapp:1.0
        ports:
            - 3000:3000 
        environment: 
            - MONGO_DB_USERNAME=admin
            - MONO_DB_PWD=password123

volumes: # all volumes used in docker compose should be listed here 
    mongo-data:
        driver: local # volume on local host system 